import type { LearningPath, LessonMeta, LessonStatus } from "@/lib/types";

// The full curriculum tree. Lessons with status "full" have complete
// interactive bodies in content/lessons; "outline" lessons are mapped
// (objectives, prereqs, difficulty) awaiting authoring in v1.5.

function L(
  slug: string,
  title: string,
  topicId: string,
  difficulty: number,
  estMinutes: number,
  summary: string,
  objectives: string[],
  prereqs: string[] = [],
  status: LessonStatus = "outline",
): LessonMeta {
  return { slug, title, topicId, difficulty, estMinutes, summary, objectives, prereqs, status };
}

export const PATHS: LearningPath[] = [
  {
    id: "foundations",
    title: "Foundations",
    tagline: "Number sense before notation.",
    description:
      "Arithmetic fluency, proportional reasoning, and estimation — rebuilt as thinking tools rather than procedures. The bedrock of every contest.",
    units: [
      {
        id: "number-fluency",
        title: "Number Fluency",
        lessons: [
          L("arithmetic-fluency", "Arithmetic as Structure", "arithmetic", 1, 25,
            "Computation reorganized around structure: regrouping, factoring, distributivity.",
            ["Compute by restructuring, not grinding", "Exploit the distributive law", "Recognize friendly numbers"]),
          L("mental-math", "Mental Math & Clever Computation", "arithmetic", 2, 25,
            "Contest-speed computation: difference of squares, pairing, telescoping sums.",
            ["Square and multiply mentally", "Pair terms in long sums", "Choose the fastest route"],
            ["arithmetic-fluency"]),
          L("estimation-number-sense", "Estimation & Number Sense", "estimation", 2, 30,
            "Bounding, approximation, and the art of knowing roughly — before knowing exactly.",
            ["Bound quantities above and below", "Estimate products, quotients, and roots", "Use estimates to eliminate answer choices"],
            ["arithmetic-fluency"], "full"),
        ],
      },
      {
        id: "proportional-reasoning",
        title: "Proportional Reasoning",
        lessons: [
          L("fractions-core", "Fractions, Deeply", "fractions-ratios", 2, 30,
            "Fractions as division, as ratio, as operator — and the arithmetic that follows.",
            ["Interpret fractions three ways", "Compare fractions without common denominators", "Handle complex fractions"]),
          L("ratios-proportional-reasoning", "Ratios & Proportional Reasoning", "fractions-ratios", 3, 35,
            "The ratio toolbox: scaling, sharing, mixing, and the part-to-whole shift that unlocks contest problems.",
            ["Translate between ratios and fractions of a whole", "Scale ratios through shared quantities", "Solve mixture and rate problems by ratio"],
            ["fractions-core"], "full"),
          L("percents-rates", "Percents, Rates & Averages", "percents", 3, 30,
            "Percent change, successive discounts, weighted averages, and rate problems.",
            ["Compose percent changes multiplicatively", "Set up rate equations", "Use weighted averages"],
            ["ratios-proportional-reasoning"]),
        ],
      },
      {
        id: "habits",
        title: "Habits of Mind",
        lessons: [
          L("problem-solving-habits", "How to Attack a Problem", "estimation", 2, 25,
            "Polya's cycle adapted for contests: understand, plan, execute, review.",
            ["Restate problems in your own words", "Try small cases first", "Check answers for reasonableness"]),
        ],
      },
    ],
  },
  {
    id: "pre-algebra",
    title: "Pre-Algebra",
    tagline: "The language of the unknown.",
    description:
      "Variables, equations, inequalities, and the coordinate plane — symbolic reasoning as a precise, powerful language.",
    units: [
      {
        id: "language-of-algebra",
        title: "The Language of Algebra",
        lessons: [
          L("variables-expressions", "Variables & Expressions", "expressions", 2, 25,
            "Naming unknowns, building expressions, and simplifying with intent.",
            ["Translate words into expressions", "Simplify strategically", "Substitute and evaluate"]),
          L("linear-equations-mastery", "Linear Equations Mastery", "linear-equations", 3, 35,
            "Solving is the easy part — the art is setting up. Word problems, systems in disguise, and clever substitutions.",
            ["Model word problems with equations", "Solve linear equations fluently", "Spot when a substitution collapses a problem"],
            ["variables-expressions"], "full"),
          L("inequalities-intro", "Inequalities & Bounding", "inequalities-basic", 3, 30,
            "Direction-flipping, chaining, and using inequalities to trap integer answers.",
            ["Manipulate inequalities safely", "Chain bounds", "Trap integers between bounds"],
            ["linear-equations-mastery"]),
          L("absolute-value", "Absolute Value & Distance", "inequalities-basic", 3, 25,
            "Absolute value as distance; equations and inequalities by cases and by picture.",
            ["Read |x−a| as distance", "Split into cases cleanly", "Solve graphically"],
            ["inequalities-intro"]),
        ],
      },
      {
        id: "the-plane",
        title: "The Plane",
        lessons: [
          L("coordinate-plane-basics", "The Coordinate Plane", "coordinate-plane", 3, 30,
            "Points, slopes, lines, midpoints, distance — geometry with coordinates.",
            ["Compute slope and distance", "Write line equations", "Use midpoints and intercepts"],
            ["linear-equations-mastery"]),
          L("word-problems-modeling", "Modeling Word Problems", "linear-equations", 4, 30,
            "Age, work, motion, and mixture problems — one setup discipline for all of them.",
            ["Define variables precisely", "Build equations from relationships", "Sanity-check with units"],
            ["linear-equations-mastery"]),
        ],
      },
    ],
  },
  {
    id: "algebra",
    title: "Algebra",
    tagline: "Structure is the shortcut.",
    description:
      "Functions, polynomials, quadratics, systems, and sequences — where recognizing structure replaces brute force.",
    units: [
      {
        id: "functions-polynomials",
        title: "Functions & Polynomials",
        lessons: [
          L("functions-intro", "Functions & Transformations", "functions", 4, 30,
            "Function notation, composition, inverses, and graph transformations.",
            ["Compose and invert functions", "Shift, stretch, and reflect graphs", "Read functional notation fluently"],
            ["coordinate-plane-basics"]),
          L("polynomial-toolbox", "The Polynomial Toolbox", "polynomials", 5, 35,
            "Factoring patterns, the remainder theorem, and root-coefficient thinking.",
            ["Factor with standard identities", "Apply remainder & factor theorems", "Count and locate roots"],
            ["functions-intro"]),
          L("quadratics-vieta", "Quadratics & Vieta's Formulas", "quadratics", 5, 40,
            "The complete quadratic: vertex form, discriminants, and Vieta's formulas — the contest workhorse.",
            ["Convert between quadratic forms", "Use the discriminant to reason about roots", "Apply Vieta's formulas to symmetric expressions"],
            ["polynomial-toolbox"], "full"),
        ],
      },
      {
        id: "structure",
        title: "Structure & Pattern",
        lessons: [
          L("systems-symmetry", "Systems & Symmetry", "systems", 5, 30,
            "Solving systems by elimination, substitution — and by noticing symmetry first.",
            ["Solve 2- and 3-variable systems", "Add equations to exploit symmetry", "Substitute aggregates like x+y"],
            ["quadratics-vieta"]),
          L("sequences-telescoping", "Sequences, Series & Telescoping", "sequences", 5, 40,
            "Arithmetic and geometric sequences, then the telescoping idea that collapses monsters.",
            ["Sum arithmetic and geometric series", "Recognize telescoping structure", "Partial-fraction a telescoping term"],
            ["polynomial-toolbox"], "full"),
          L("exponents-radicals", "Exponents & Radicals", "polynomials", 4, 25,
            "Exponent laws, radical manipulation, and rationalization under pressure.",
            ["Apply exponent laws fluently", "Denest and rationalize radicals", "Compare exponential quantities"],
            ["variables-expressions"]),
          L("logarithms-intro", "Logarithms", "functions", 5, 30,
            "Logs as inverse exponentials; the identities and the classic contest patterns.",
            ["Convert between exp and log form", "Apply log identities", "Solve log equations"],
            ["exponents-radicals"]),
        ],
      },
    ],
  },
  {
    id: "geometry",
    title: "Geometry",
    tagline: "See the invisible line.",
    description:
      "From angle chasing to power of a point — training the eye to see the auxiliary line, the hidden similar triangle, the circle nobody drew.",
    units: [
      {
        id: "angles-triangles",
        title: "Angles & Triangles",
        lessons: [
          L("angle-chasing", "Angle Chasing", "angles", 3, 35,
            "Parallel lines, triangle sums, isosceles symmetry — the deductive game every geometer plays first.",
            ["Chase angles through parallel lines", "Use triangle and polygon angle sums", "Exploit isosceles triangles"],
            [], "full"),
          L("triangle-toolkit", "The Triangle Toolkit", "triangles", 4, 35,
            "Congruence, the triangle inequality, medians, altitudes, and area formulas.",
            ["Prove triangles congruent", "Apply the triangle inequality", "Compute area five ways"],
            ["angle-chasing"]),
          L("special-triangles", "Special Right Triangles & Pythagoras", "triangles", 4, 30,
            "45-45-90, 30-60-90, Pythagorean triples, and distance in disguise.",
            ["Recall special ratios instantly", "Recognize Pythagorean triples", "Drop the right altitude"],
            ["triangle-toolkit"]),
        ],
      },
      {
        id: "scaling-circles",
        title: "Scaling & Circles",
        lessons: [
          L("similar-triangles", "Similar Triangles", "similarity", 5, 40,
            "AA similarity and ratio bookkeeping — the single most-used tool in contest geometry.",
            ["Spot AA similarity in configurations", "Track ratios through similar pairs", "Use similarity to compute lengths"],
            ["triangle-toolkit"], "full"),
          L("circle-theorems", "Circles & Inscribed Angles", "circles", 5, 35,
            "Central and inscribed angles, arcs, tangents, and cyclic quadrilaterals.",
            ["Apply the inscribed angle theorem", "Use tangent-radius perpendicularity", "Recognize cyclic quadrilaterals"],
            ["angle-chasing"]),
          L("power-of-a-point", "Power of a Point", "circles", 6, 30,
            "Chord-chord, secant-secant, tangent-secant — one theorem, three costumes.",
            ["State power of a point in all forms", "Choose the right configuration", "Combine with similarity"],
            ["circle-theorems", "similar-triangles"]),
        ],
      },
      {
        id: "analytic-solid",
        title: "Analytic & Solid",
        lessons: [
          L("coordinate-geometry-methods", "Coordinate Methods", "coordinate-geometry", 5, 35,
            "When synthetic fails, coordinatize: distance, area by Shoelace, clever placement.",
            ["Place figures to simplify algebra", "Compute areas with the Shoelace formula", "Know when to coordinatize"],
            ["coordinate-plane-basics", "special-triangles"]),
          L("area-techniques", "Area Techniques", "triangles", 5, 30,
            "Decomposition, ratios of areas, and same-base-same-height reasoning.",
            ["Decompose complex regions", "Relate areas through shared heights", "Use ratio arguments"],
            ["triangle-toolkit"]),
          L("solid-geometry-intuition", "3D Geometry", "solid-geometry", 6, 35,
            "Volumes, surface areas, cross-sections, and unfolding tricks.",
            ["Compute standard volumes", "Reason about cross-sections", "Unfold surfaces for shortest paths"],
            ["special-triangles"]),
          L("transformations-intro", "Transformations", "coordinate-geometry", 6, 30,
            "Reflections, rotations, translations — symmetry as a solving tool.",
            ["Reflect to straighten paths", "Rotate to align structures", "Compose transformations"],
            ["coordinate-geometry-methods"]),
          L("trigonometry-toolkit", "Trigonometry for Contests", "triangles", 6, 35,
            "Law of sines and cosines, area by sine, and identity fluency.",
            ["Apply laws of sines and cosines", "Compute area via ½ab·sin C", "Use key identities"],
            ["special-triangles"]),
        ],
      },
    ],
  },
  {
    id: "counting",
    title: "Counting & Probability",
    tagline: "Count what you cannot list.",
    description:
      "From the product rule to expected value — combinatorial reasoning, the most learnable superpower in competition math.",
    units: [
      {
        id: "art-of-counting",
        title: "The Art of Counting",
        lessons: [
          L("counting-fundamentals", "Counting Fundamentals", "counting-basics", 3, 35,
            "The product rule, the sum rule, and the discipline of counting without double-counting.",
            ["Apply product and sum rules correctly", "Detect and correct double counting", "Count by building objects step by step"],
            [], "full"),
          L("permutations-combinations", "Permutations & Combinations", "perms-combs", 4, 35,
            "Arrangements, selections, and the bridge between them — with repeated elements handled honestly.",
            ["Choose between nPr and nCr", "Handle repeated objects", "Count circular arrangements"],
            ["counting-fundamentals"]),
          L("casework-complementary", "Casework & Complementary Counting", "casework", 5, 40,
            "Splitting problems into clean cases — and the liberating move of counting what you don't want.",
            ["Partition into exhaustive, disjoint cases", "Recognize when complementary counting wins", "Combine casework with the product rule"],
            ["permutations-combinations"], "full"),
          L("binomial-theorem", "The Binomial Theorem", "perms-combs", 5, 30,
            "Pascal's triangle, binomial identities, and coefficient extraction.",
            ["Expand with the binomial theorem", "Prove identities combinatorially", "Extract coefficients"],
            ["permutations-combinations"]),
        ],
      },
      {
        id: "probability-expectation",
        title: "Probability & Expectation",
        lessons: [
          L("probability-foundations", "Probability Foundations", "probability", 4, 35,
            "Sample spaces, equally likely outcomes, independence, and conditional probability.",
            ["Build sample spaces explicitly", "Multiply along independent events", "Compute conditional probabilities"],
            ["counting-fundamentals"]),
          L("expected-value", "Expected Value & Linearity", "expected-value", 6, 40,
            "The most elegant tool in probability: linearity of expectation, indicators, and why it works even with dependence.",
            ["Compute expected value from definitions", "Apply linearity of expectation", "Design indicator variables"],
            ["probability-foundations"], "full"),
          L("pigeonhole-principle", "The Pigeonhole Principle", "pigeonhole", 5, 30,
            "Existence by counting: if there are more pigeons than holes, two share.",
            ["State and apply pigeonhole", "Choose the right holes", "Use the generalized version"],
            ["counting-fundamentals"]),
          L("geometric-probability", "Geometric Probability", "probability", 6, 30,
            "Probability as area — continuous sample spaces and clever regions.",
            ["Model with regions", "Compute area ratios", "Handle time-interval meeting problems"],
            ["probability-foundations", "coordinate-plane-basics"]),
          L("recursion-counting", "Counting with Recursion", "casework", 6, 35,
            "States, transitions, and the recurrences behind tiling and path problems.",
            ["Define states and transitions", "Set up recurrences", "Compute by building up"],
            ["casework-complementary"]),
        ],
      },
    ],
  },
  {
    id: "number-theory",
    title: "Number Theory",
    tagline: "The integers keep secrets.",
    description:
      "Divisibility, congruences, and Diophantine equations — the oldest playground in mathematics and the sharpest section of every contest.",
    units: [
      {
        id: "divisibility-unit",
        title: "Divisibility & Primes",
        lessons: [
          L("divisibility-primes", "Divisibility & Prime Factorization", "divisibility", 4, 35,
            "The fundamental theorem of arithmetic and everything it buys: divisor counts, gcd, lcm.",
            ["Factor and count divisors", "Compute gcd and lcm structurally", "Use p-adic (exponent) thinking"],
            []),
          L("gcd-lcm-structure", "GCD, LCM & the Euclidean Algorithm", "divisibility", 5, 30,
            "The Euclidean algorithm, Bezout's identity, and gcd·lcm = product.",
            ["Run the Euclidean algorithm", "Apply gcd·lcm = ab", "Use Bezout for existence arguments"],
            ["divisibility-primes"]),
          L("number-bases", "Number Bases & Digits", "divisibility", 4, 30,
            "Base-b representation, digit sums, and divisibility rules that fall out of them.",
            ["Convert between bases", "Prove divisibility rules", "Solve digit puzzles"],
            ["divisibility-primes"]),
        ],
      },
      {
        id: "congruences-unit",
        title: "Congruences",
        lessons: [
          L("modular-arithmetic", "Modular Arithmetic", "modular", 5, 40,
            "Clock arithmetic made rigorous: congruences, cycles of powers, and the remainder questions contests love.",
            ["Compute with congruences fluently", "Find cycles in powers mod n", "Solve linear congruences"],
            ["divisibility-primes"], "full"),
          L("diophantine-methods", "Diophantine Equations", "diophantine", 6, 35,
            "Integer-solution hunting: factoring tricks, bounding, and Simon's Favorite Factoring Trick.",
            ["Factor to force integer constraints", "Bound solutions before searching", "Apply SFFT"],
            ["modular-arithmetic"]),
          L("totient-crt-advanced", "Euler's Theorem & CRT", "totient-crt", 7, 40,
            "The totient function, Euler's theorem, Fermat's little theorem, and the Chinese Remainder Theorem.",
            ["Compute φ(n)", "Reduce huge exponents with Euler", "Solve simultaneous congruences with CRT"],
            ["modular-arithmetic"]),
        ],
      },
    ],
  },
  {
    id: "olympiad",
    title: "Olympiad Topics",
    tagline: "Where technique ends, thought begins.",
    description:
      "Invariants, extremal arguments, functional equations, graph theory — the proof-based ideas that separate qualifiers from medalists.",
    units: [
      {
        id: "combinatorial-essence",
        title: "Combinatorial Essence",
        lessons: [
          L("invariants-monovariants", "Invariants & Monovariants", "invariants", 7, 45,
            "The olympiad opener: find what a process preserves, and impossibility proofs write themselves.",
            ["Identify invariants of a process", "Use parity and coloring arguments", "Deploy monovariants for termination"],
            ["pigeonhole-principle", "modular-arithmetic"], "full"),
          L("extremal-principle", "The Extremal Principle", "extremal", 7, 40,
            "Consider the largest, the smallest, the closest pair — and let extremity do the work.",
            ["Choose the right extremal object", "Derive contradictions from extremality", "Combine with induction"],
            ["invariants-monovariants"]),
          L("graph-theory-first-steps", "Graph Theory, First Steps", "graph-theory", 7, 40,
            "Vertices, edges, degrees, connectivity — and the handshake lemma's surprising reach.",
            ["Model problems as graphs", "Apply the handshake lemma", "Argue about connectivity and cycles"],
            ["counting-fundamentals"]),
          L("generating-functions-intro", "Generating Functions", "generating-functions", 8, 45,
            "Counting with power series: convolution, partitions, and closed forms.",
            ["Encode sequences as series", "Multiply generating functions to convolve", "Extract coefficients"],
            ["binomial-theorem", "sequences-telescoping"]),
        ],
      },
      {
        id: "algebraic-arts",
        title: "Algebraic Arts",
        lessons: [
          L("functional-equations-intro", "Functional Equations", "functional-equations", 8, 45,
            "Substitution discipline, injectivity and surjectivity, and the Cauchy equation.",
            ["Make systematic substitutions", "Prove injectivity/surjectivity", "Recognize Cauchy-type equations"],
            ["functions-intro"]),
          L("recursion-mastery", "Recursive Sequences", "recursion", 7, 40,
            "Linear recurrences, characteristic roots, and periodicity hunting.",
            ["Solve linear recurrences", "Find and prove periodicity", "Translate recursions into closed forms"],
            ["sequences-telescoping"]),
          L("olympiad-inequalities", "Olympiad Inequalities", "inequalities-olympiad", 8, 45,
            "AM-GM, Cauchy-Schwarz, and the strategy of smoothing and normalization.",
            ["Apply AM-GM and Cauchy-Schwarz", "Normalize cleverly", "Find equality cases first"],
            ["quadratics-vieta"]),
        ],
      },
      {
        id: "geometry-at-depth",
        title: "Geometry at Depth",
        lessons: [
          L("cyclic-quadrilaterals", "Cyclic Quadrilaterals & Angle Hunting", "olympiad-geometry", 8, 40,
            "Ptolemy, cyclic characterizations, and the concyclic points nobody mentioned.",
            ["Prove points concyclic", "Apply Ptolemy's theorem", "Chase directed angles"],
            ["circle-theorems", "power-of-a-point"]),
          L("advanced-configurations", "Advanced Configurations", "olympiad-geometry", 9, 45,
            "Radical axes, homothety, and the classical configurations of olympiad geometry.",
            ["Use radical axes", "Spot homothety centers", "Recognize classical configurations"],
            ["cyclic-quadrilaterals"]),
          L("olympiad-proof-writing", "Proof Writing", "extremal", 7, 40,
            "The craft of the written proof: structure, rigor, and the reader's experience.",
            ["Structure proofs clearly", "Close logical gaps", "Write for a grader"],
            ["invariants-monovariants"]),
        ],
      },
    ],
  },
];

// ── derived indices ─────────────────────────────────────────────

export const allLessons: LessonMeta[] = PATHS.flatMap(p => p.units.flatMap(u => u.lessons));
export const lessonBySlug = new Map(allLessons.map(l => [l.slug, l]));
export const pathById = new Map(PATHS.map(p => [p.id, p]));

export function pathOfLesson(slug: string): LearningPath | undefined {
  return PATHS.find(p => p.units.some(u => u.lessons.some(l => l.slug === slug)));
}
