import type { Problem } from "@/lib/types";

export const ALGEBRA_PROBLEMS: Problem[] = [
  {
    id: "func-1",
    statement: "If $f(x) = 2x + 3$, what is $f(f(2))$?",
    answerType: "integer",
    answer: 17,
    difficulty: 4,
    estMinutes: 2,
    topicId: "functions",
    subtopic: "Composition",
    source: "AMC 10 style",
    tags: ["composition"],
    hints: [
      "Work from the inside out.",
      "First compute $f(2)$.",
      "$f(2) = 7$; now apply $f$ again.",
    ],
    solution: "$f(2) = 7$, then $f(7) = 2 \\cdot 7 + 3 = 17$.",
  },
  {
    id: "func-2",
    statement: "What is the minimum value of $f(x) = x^2 - 4x + 7$?",
    answerType: "integer",
    answer: 3,
    difficulty: 5,
    estMinutes: 3,
    topicId: "functions",
    subtopic: "Vertex form",
    source: "AMC 10 style",
    tags: ["quadratics", "completing-square"],
    hints: [
      "Complete the square.",
      "$x^2 - 4x + 7 = (x-2)^2 + \\,?$",
      "$(x-2)^2 \\ge 0$ always, with equality at $x = 2$.",
    ],
    solution:
      "$f(x) = (x-2)^2 + 3 \\ge 3$, with equality at $x = 2$. Minimum: $3$.",
    related: ["quad-3"],
  },
  {
    id: "func-3",
    statement:
      "Solve for $x$: $\\log_2 x + \\log_2 (x - 2) = 3$.",
    answerType: "integer",
    answer: 4,
    difficulty: 6,
    estMinutes: 4,
    topicId: "functions",
    subtopic: "Logarithmic equations",
    source: "AMC 12 style",
    tags: ["logarithms"],
    hints: [
      "Combine the logs into one.",
      "$\\log_2 [x(x-2)] = 3$ means $x(x-2) = 8$.",
      "Solve the quadratic, then check the domain: both logs need positive inputs.",
    ],
    solution:
      "$x(x-2) = 2^3 = 8$ gives $x^2 - 2x - 8 = 0 = (x-4)(x+2)$, so $x = 4$ or $x = -2$. Only $x = 4$ keeps both logarithms defined.",
    commonMistakes: ["Keeping $x = -2$ — always check log domains."],
  },
  {
    id: "poly-1",
    statement:
      "What is the remainder when $x^3 - 2x^2 + 3x - 4$ is divided by $x - 2$?",
    answerType: "integer",
    answer: 2,
    difficulty: 5,
    estMinutes: 2,
    topicId: "polynomials",
    subtopic: "Remainder theorem",
    source: "AMC 10 style",
    tags: ["remainder-theorem"],
    hints: [
      "No long division needed.",
      "The Remainder Theorem: dividing by $x - a$ leaves remainder $P(a)$.",
      "Evaluate the polynomial at $x = 2$.",
    ],
    solution:
      "By the Remainder Theorem, the remainder is $P(2) = 8 - 8 + 6 - 4 = 2$.",
  },
  {
    id: "poly-2",
    statement: "What is the sum of the coefficients of $(2x - 1)^4$?",
    answerType: "integer",
    answer: 1,
    difficulty: 5,
    estMinutes: 2,
    topicId: "polynomials",
    subtopic: "Coefficient tricks",
    source: "AMC 10 style",
    tags: ["evaluation-trick"],
    hints: [
      "Expanding is a trap. What operation extracts a coefficient sum?",
      "The sum of coefficients of $P(x)$ is $P(1)$.",
      "Evaluate $(2 \\cdot 1 - 1)^4$.",
    ],
    solution:
      "The sum of coefficients of any polynomial $P$ is $P(1)$. Here $P(1) = (2-1)^4 = 1$.",
    commonMistakes: ["Expanding all five terms — legal, slow, and error-prone."],
  },
  {
    id: "poly-3",
    statement: "If $x^2 + y^2 = 25$ and $x + y = 7$, what is $xy$?",
    answerType: "integer",
    answer: 12,
    difficulty: 5,
    estMinutes: 3,
    topicId: "polynomials",
    subtopic: "Symmetric identities",
    source: "AMC 10 style",
    tags: ["identities", "symmetric"],
    hints: [
      "Relate the two givens through $(x+y)^2$.",
      "$(x+y)^2 = x^2 + 2xy + y^2$.",
      "$49 = 25 + 2xy$.",
    ],
    solution: "$(x+y)^2 = x^2 + y^2 + 2xy$ gives $49 = 25 + 2xy$, so $xy = 12$.",
    related: ["expr-1", "sys-2"],
  },
  {
    id: "quad-1",
    statement:
      "The roots of $x^2 - 7x + 12 = 0$ are $r$ and $s$. What is $r^2 + s^2$?",
    answerType: "integer",
    answer: 25,
    difficulty: 4,
    estMinutes: 3,
    topicId: "quadratics",
    subtopic: "Vieta's formulas",
    source: "AMC 10 style",
    tags: ["vieta"],
    hints: [
      "You don't need the roots themselves.",
      "Vieta: $r + s = 7$, $rs = 12$.",
      "$r^2 + s^2 = (r+s)^2 - 2rs$.",
    ],
    solution:
      "By Vieta, $r+s = 7$ and $rs = 12$, so $r^2+s^2 = 49 - 24 = 25$.",
    altSolutions: ["Factor: roots are $3$ and $4$; $9 + 16 = 25$. Works here, but Vieta scales to problems where factoring doesn't."],
  },
  {
    id: "quad-2",
    statement:
      "If $r$ and $s$ are the roots of $x^2 - 6x + 4 = 0$, what is $\\tfrac{1}{r} + \\tfrac{1}{s}$?",
    answerType: "mcq",
    choices: ["$\\tfrac{2}{3}$", "$1$", "$\\tfrac{3}{2}$", "$2$", "$3$"],
    answer: 2,
    difficulty: 5,
    estMinutes: 3,
    topicId: "quadratics",
    subtopic: "Vieta's formulas",
    source: "AMC 10 style",
    tags: ["vieta", "manipulation"],
    hints: [
      "Combine the fractions first.",
      "$\\tfrac1r + \\tfrac1s = \\tfrac{r+s}{rs}$.",
      "Read $r+s$ and $rs$ off the coefficients.",
    ],
    solution:
      "$\\tfrac1r + \\tfrac1s = \\tfrac{r+s}{rs} = \\tfrac{6}{4} = \\tfrac32$.",
    commonMistakes: ["Computing the roots with the quadratic formula — the surds cancel, but slowly."],
    related: ["quad-1"],
  },
  {
    id: "quad-3",
    statement:
      "For what positive value of $k$ does $x^2 + kx + 9 = 0$ have exactly one solution?",
    answerType: "integer",
    answer: 6,
    difficulty: 5,
    estMinutes: 3,
    topicId: "quadratics",
    subtopic: "Discriminant",
    source: "AMC 10 style",
    tags: ["discriminant"],
    hints: [
      "One solution means the quadratic is a perfect square.",
      "Set the discriminant $k^2 - 4 \\cdot 9$ to zero.",
      "$k^2 = 36$, and you want the positive root.",
    ],
    solution:
      "Exactly one root requires discriminant zero: $k^2 - 36 = 0$, so $k = 6$ (taking the positive value). Indeed $x^2 + 6x + 9 = (x+3)^2$.",
  },
  {
    id: "quad-4",
    statement:
      "The cubic $x^3 - 6x^2 + 11x - 6 = 0$ has roots $p, q, r$. What is $pq + qr + rp$?",
    answerType: "integer",
    answer: 11,
    difficulty: 6,
    estMinutes: 3,
    topicId: "quadratics",
    subtopic: "Vieta for cubics",
    source: "AMC 12 style",
    tags: ["vieta", "cubic"],
    hints: [
      "Vieta extends to any degree.",
      "For $x^3 + ax^2 + bx + c$: the pairwise product sum is $b$.",
      "Read it straight off the coefficient of $x$.",
    ],
    solution:
      "For a monic cubic $x^3 + ax^2 + bx + c$ with roots $p,q,r$: $pq+qr+rp = b = 11$. (The roots happen to be $1, 2, 3$: check $2 + 6 + 3 = 11$.)",
  },
  {
    id: "sys-1",
    statement: "If $x + y = 10$ and $x^2 - y^2 = 40$, what is $x$?",
    answerType: "integer",
    answer: 7,
    difficulty: 5,
    estMinutes: 3,
    topicId: "systems",
    subtopic: "Factoring systems",
    source: "AMC 10 style",
    tags: ["difference-of-squares", "systems"],
    hints: [
      "Factor the second equation.",
      "$x^2 - y^2 = (x+y)(x-y) = 40$, and you know $x + y$.",
      "So $x - y = 4$; add the two linear equations.",
    ],
    solution:
      "$(x+y)(x-y) = 40$ with $x+y = 10$ gives $x - y = 4$. Adding: $2x = 14$, $x = 7$.",
  },
  {
    id: "sys-2",
    statement: "If $x + y = 5$ and $xy = 6$, what is $x^3 + y^3$?",
    answerType: "integer",
    answer: 35,
    difficulty: 6,
    estMinutes: 4,
    topicId: "systems",
    subtopic: "Power sums",
    source: "AMC 12 style",
    tags: ["identities", "symmetric", "newton-sums"],
    hints: [
      "There's an identity for $x^3 + y^3$ in terms of $x+y$ and $xy$.",
      "$x^3 + y^3 = (x+y)^3 - 3xy(x+y)$.",
      "Substitute $5$ and $6$.",
    ],
    solution:
      "$x^3+y^3 = (x+y)^3 - 3xy(x+y) = 125 - 90 = 35$. (The pair is $\\{2,3\\}$: $8 + 27 = 35$.)",
    related: ["poly-3", "expr-1"],
  },
  {
    id: "seq-1",
    statement:
      "An arithmetic sequence has first term $5$ and common difference $3$. What is its $20$th term?",
    answerType: "integer",
    answer: 62,
    difficulty: 4,
    estMinutes: 2,
    topicId: "sequences",
    subtopic: "Arithmetic sequences",
    source: "AMC 8 style",
    tags: ["arithmetic-sequence"],
    hints: [
      "How many steps from term 1 to term 20?",
      "Nineteen steps of size $3$.",
      "$a_{20} = 5 + 19 \\cdot 3$.",
    ],
    solution: "$a_{20} = a_1 + 19d = 5 + 57 = 62$.",
    commonMistakes: ["Using $20d$ instead of $19d$ — the fencepost error."],
  },
  {
    id: "seq-2",
    statement:
      "An infinite geometric series has first term $6$ and ratio $\\tfrac{1}{3}$. What is its sum?",
    answerType: "integer",
    answer: 9,
    difficulty: 5,
    estMinutes: 2,
    topicId: "sequences",
    subtopic: "Geometric series",
    source: "AMC 10 style",
    tags: ["geometric-series"],
    hints: [
      "There is a closed form when $|r| < 1$.",
      "$S = \\tfrac{a}{1 - r}$.",
      "$\\tfrac{6}{1 - 1/3} = \\tfrac{6}{2/3}$.",
    ],
    solution: "$S = \\tfrac{a}{1-r} = \\tfrac{6}{2/3} = 9$.",
  },
  {
    id: "seq-3",
    statement:
      "Let $S = \\sum_{k=1}^{99} \\tfrac{1}{k(k+1)}$. If $S = \\tfrac{m}{n}$ in lowest terms, what is $m + n$?",
    answerType: "integer",
    answer: 199,
    difficulty: 7,
    estMinutes: 5,
    topicId: "sequences",
    subtopic: "Telescoping",
    source: "AIME style",
    tags: ["telescoping", "partial-fractions"],
    hints: [
      "Split each term with partial fractions.",
      "$\\tfrac{1}{k(k+1)} = \\tfrac1k - \\tfrac1{k+1}$.",
      "Everything cancels except the first and last pieces.",
    ],
    solution:
      "Each term telescopes: $S = \\left(1 - \\tfrac12\\right) + \\left(\\tfrac12 - \\tfrac13\\right) + \\cdots + \\left(\\tfrac1{99} - \\tfrac1{100}\\right) = 1 - \\tfrac1{100} = \\tfrac{99}{100}$. So $m + n = 199$.",
    commonMistakes: ["Summing decimals numerically — the structure is the whole point."],
  },
  {
    id: "seq-4",
    statement:
      "A sequence satisfies $a_1 = 1$ and $a_n = a_{n-1} + 2n - 1$ for $n \\ge 2$. What is $a_{15}$?",
    answerType: "integer",
    answer: 225,
    difficulty: 6,
    estMinutes: 4,
    topicId: "sequences",
    subtopic: "Recognizing closed forms",
    source: "AMC 10 style",
    tags: ["recursion", "pattern"],
    hints: [
      "Compute the first few terms and stare.",
      "$1, 4, 9, 16, \\ldots$",
      "Adding consecutive odd numbers builds perfect squares.",
    ],
    solution:
      "The recursion adds successive odd numbers, and $1 + 3 + \\cdots + (2n-1) = n^2$, so $a_n = n^2$ and $a_{15} = 225$.",
  },
];
