import type { Problem } from "@/lib/types";

// Foundations & Pre-Algebra bank. All problems are original,
// written in the style of the cited contests.

export const FOUNDATIONS_PROBLEMS: Problem[] = [
  {
    id: "arith-1",
    statement: "Compute $48 \\cdot 25 + 52 \\cdot 25$.",
    answerType: "mcq",
    choices: ["$1250$", "$2000$", "$2400$", "$2500$", "$2600$"],
    answer: 3,
    difficulty: 1,
    estMinutes: 1,
    topicId: "arithmetic",
    subtopic: "Distributive law",
    source: "AMC 8 style",
    tags: ["distributive", "mental-math"],
    hints: [
      "Don't multiply anything yet. Look at what the two products share.",
      "Both terms have a factor of 25. Factor it out.",
      "$48 \\cdot 25 + 52 \\cdot 25 = (48 + 52) \\cdot 25 = 100 \\cdot 25$.",
    ],
    solution:
      "Factor out the common $25$: $(48 + 52)\\cdot 25 = 100 \\cdot 25 = 2500$. The distributive law turns two multiplications into one trivial one.",
    commonMistakes: ["Computing each product separately and making an arithmetic slip along the way."],
    related: ["arith-3"],
  },
  {
    id: "arith-2",
    statement: "Compute $1 + 2 + 3 + \\cdots + 40$.",
    answerType: "integer",
    answer: 820,
    difficulty: 2,
    estMinutes: 2,
    topicId: "arithmetic",
    subtopic: "Summation",
    source: "MathCounts style",
    tags: ["gauss-sum", "pairing"],
    hints: [
      "Pair the first term with the last, the second with the second-to-last…",
      "Each pair $(1+40), (2+39), \\ldots$ has the same sum. How many pairs are there?",
      "There are $20$ pairs, each summing to $41$.",
    ],
    solution:
      "Pair terms from the outside in: $1+40 = 2+39 = \\cdots = 41$, and there are $20$ such pairs, so the sum is $20 \\cdot 41 = 820$. In general $1 + \\cdots + n = \\tfrac{n(n+1)}{2}$.",
    altSolutions: ["Apply the formula directly: $\\tfrac{40 \\cdot 41}{2} = 820$."],
  },
  {
    id: "arith-3",
    statement: "Compute $999 \\cdot 1001$.",
    answerType: "integer",
    answer: 999999,
    difficulty: 3,
    estMinutes: 2,
    topicId: "arithmetic",
    subtopic: "Difference of squares",
    source: "AMC 8 style",
    tags: ["difference-of-squares", "mental-math"],
    hints: [
      "Both numbers are close to a very round number.",
      "Write the product as $(1000 - 1)(1000 + 1)$.",
      "Use $(a-b)(a+b) = a^2 - b^2$.",
    ],
    solution:
      "$999 \\cdot 1001 = (1000-1)(1000+1) = 1000^2 - 1^2 = 999999$.",
    commonMistakes: ["Multiplying digit-by-digit and slipping; the identity is safer."],
    related: ["arith-1", "arith-4"],
  },
  {
    id: "arith-4",
    statement: "Compute $17^2 - 13^2$.",
    answerType: "integer",
    answer: 120,
    difficulty: 2,
    estMinutes: 1,
    topicId: "arithmetic",
    subtopic: "Difference of squares",
    source: "MathCounts style",
    tags: ["difference-of-squares"],
    hints: [
      "Resist squaring. There is a factored form.",
      "$a^2 - b^2 = (a-b)(a+b)$.",
      "$(17-13)(17+13) = 4 \\cdot 30$.",
    ],
    solution: "$17^2 - 13^2 = (17-13)(17+13) = 4 \\cdot 30 = 120$.",
    related: ["arith-3"],
  },
  {
    id: "frac-1",
    statement: "What is $\\tfrac{3}{4}$ of $\\tfrac{2}{5}$ of $200$?",
    answerType: "integer",
    answer: 60,
    difficulty: 2,
    estMinutes: 1,
    topicId: "fractions-ratios",
    subtopic: "Fraction of a quantity",
    source: "AMC 8 style",
    tags: ["fractions"],
    hints: [
      "“Of” means multiply.",
      "Work right to left: first find $\\tfrac{2}{5}$ of $200$.",
      "$\\tfrac{2}{5} \\cdot 200 = 80$, then take $\\tfrac{3}{4}$ of that.",
    ],
    solution: "$\\tfrac{2}{5} \\cdot 200 = 80$ and $\\tfrac{3}{4} \\cdot 80 = 60$.",
  },
  {
    id: "ratio-1",
    statement:
      "Two numbers are in the ratio $3:5$ and their sum is $96$. What is the larger number?",
    answerType: "integer",
    answer: 60,
    difficulty: 3,
    estMinutes: 2,
    topicId: "fractions-ratios",
    subtopic: "Ratio and sum",
    source: "AMC 8 style",
    tags: ["ratios", "parts"],
    hints: [
      "Think in “parts”: the numbers are $3$ parts and $5$ parts.",
      "How many parts in total, and what is one part worth?",
      "$8$ parts $= 96$, so one part $= 12$.",
    ],
    solution:
      "The total is $3+5 = 8$ parts, so one part is $96/8 = 12$. The larger number is $5 \\cdot 12 = 60$.",
    commonMistakes: ["Answering the smaller number ($36$) — read what is asked."],
  },
  {
    id: "ratio-2",
    statement:
      "If $a:b = 2:3$ and $b:c = 4:5$, and $c = 45$, what is $a$?",
    answerType: "integer",
    answer: 24,
    difficulty: 4,
    estMinutes: 3,
    topicId: "fractions-ratios",
    subtopic: "Chaining ratios",
    source: "AMC 8 style",
    tags: ["ratios", "chaining"],
    hints: [
      "The two ratios disagree about $b$. Rescale them so $b$ matches.",
      "Use $b = 12$: then $a:b = 8:12$ and $b:c = 12:15$.",
      "So $a:c = 8:15$, and $c = 45$ is three times $15$.",
    ],
    solution:
      "Rescale to a common $b$: $a:b = 8:12$ and $b:c = 12:15$, so $a:b:c = 8:12:15$. Since $c = 45 = 3 \\cdot 15$, we get $a = 3 \\cdot 8 = 24$.",
    related: ["ratio-1"],
  },
  {
    id: "ratio-3",
    statement:
      "A chemist mixes $30$ liters of $40\\%$ acid solution with $20$ liters of $10\\%$ acid solution. What is the acid concentration of the mixture?",
    answerType: "mcq",
    choices: ["$20\\%$", "$24\\%$", "$25\\%$", "$28\\%$", "$30\\%$"],
    answer: 3,
    difficulty: 5,
    estMinutes: 3,
    topicId: "fractions-ratios",
    subtopic: "Mixtures",
    source: "AMC 10 style",
    tags: ["mixtures", "weighted-average"],
    hints: [
      "Track the actual amount of acid, not the percentages.",
      "How many liters of pure acid does each solution contribute?",
      "$12 + 2 = 14$ liters of acid in $50$ liters total.",
    ],
    solution:
      "Acid: $0.40 \\cdot 30 = 12$ L and $0.10 \\cdot 20 = 2$ L, so $14$ L of acid in $50$ L of mixture: $14/50 = 28\\%$.",
    commonMistakes: ["Averaging $40\\%$ and $10\\%$ to get $25\\%$ — the volumes differ, so the average must be weighted."],
  },
  {
    id: "pct-1",
    statement:
      "An $\\$80$ jacket is marked up $25\\%$, then the new price is discounted $20\\%$. What is the final price in dollars?",
    answerType: "integer",
    answer: 80,
    difficulty: 3,
    estMinutes: 2,
    topicId: "percents",
    subtopic: "Successive percent change",
    source: "AMC 8 style",
    tags: ["percent-change"],
    hints: [
      "Convert each change to a multiplier.",
      "Up $25\\%$ means $\\times 1.25$; down $20\\%$ means $\\times 0.8$.",
      "$1.25 \\cdot 0.8 = 1$.",
    ],
    solution:
      "$80 \\cdot 1.25 \\cdot 0.8 = 80$. Percent changes compose by multiplication, and $1.25 \\cdot 0.8 = 1$: the changes cancel exactly.",
    commonMistakes: ["Adding percents: $+25\\% - 20\\% = +5\\%$ is wrong because the base changes."],
    related: ["pct-2"],
  },
  {
    id: "pct-2",
    statement:
      "Two successive $10\\%$ discounts are equivalent to a single discount of what percent?",
    answerType: "mcq",
    choices: ["$15\\%$", "$18\\%$", "$19\\%$", "$20\\%$", "$21\\%$"],
    answer: 2,
    difficulty: 4,
    estMinutes: 2,
    topicId: "percents",
    subtopic: "Composition of discounts",
    source: "AMC 8 style",
    tags: ["percent-change", "multipliers"],
    hints: [
      "Write each discount as a multiplier.",
      "Two discounts: $\\times 0.9 \\times 0.9$.",
      "$0.81$ of the price remains — how much came off?",
    ],
    solution:
      "Each discount multiplies the price by $0.9$, so together $0.9^2 = 0.81$: you pay $81\\%$, a $19\\%$ discount.",
    commonMistakes: ["Answering $20\\%$ by adding — the second discount acts on a smaller base."],
    related: ["pct-1"],
  },
  {
    id: "est-1",
    statement:
      "Which of the following is the largest?",
    answerType: "mcq",
    choices: ["$2^{100}$", "$3^{60}$", "$5^{40}$", "$10^{30}$", "$7^{35}$"],
    answer: 0,
    difficulty: 4,
    estMinutes: 3,
    topicId: "estimation",
    subtopic: "Comparing powers",
    source: "AMC 10 style",
    tags: ["estimation", "exponents"],
    hints: [
      "Compare everything to powers of $10$ using $2^{10} \\approx 10^3$.",
      "$2^{100} = (2^{10})^{10} \\approx (10^3)^{10} \\cdot (1.024)^{10}$.",
      "Estimate each: $2^{100} \\approx 1.27 \\times 10^{30}$, $3^{60} \\approx 4 \\times 10^{28}$, $5^{40} \\approx 9 \\times 10^{27}$, $7^{35} \\approx 4 \\times 10^{29}$.",
    ],
    solution:
      "Using $2^{10} = 1024 \\approx 10^3$: $2^{100} = 1024^{10} \\approx 1.27 \\times 10^{30}$, which edges out $10^{30}$. The others are smaller: $3^{60} = (3^3)^{20} = 27^{20} \\approx 4 \\times 10^{28}$, $5^{40} = 625^{10} \\approx 9 \\times 10^{27}$, $7^{35} \\approx 4 \\times 10^{29}$. So $2^{100}$ is largest.",
    commonMistakes: ["Comparing bases or exponents alone — you must normalize to a common scale."],
  },
  {
    id: "est-2",
    statement: "What is $\\lfloor \\sqrt{2026} \\rfloor$?",
    answerType: "integer",
    answer: 45,
    difficulty: 2,
    estMinutes: 2,
    topicId: "estimation",
    subtopic: "Root bounding",
    source: "MathCounts style",
    tags: ["estimation", "squares"],
    hints: [
      "Find nearby perfect squares.",
      "$45^2 = 2025$.",
      "Is $2026$ before or after the next perfect square?",
    ],
    solution:
      "$45^2 = 2025 \\le 2026 < 2116 = 46^2$, so $\\lfloor\\sqrt{2026}\\rfloor = 45$.",
  },
  {
    id: "lin-1",
    statement: "If $3x + 7 = 25$, what is $x$?",
    answerType: "mcq",
    choices: ["$4$", "$5$", "$6$", "$7$", "$8$"],
    answer: 2,
    difficulty: 1,
    estMinutes: 1,
    topicId: "linear-equations",
    subtopic: "One-step solving",
    source: "AMC 8 style",
    tags: ["linear"],
    hints: [
      "Undo the operations in reverse order.",
      "Subtract $7$ from both sides first.",
      "$3x = 18$.",
    ],
    solution: "$3x = 25 - 7 = 18$, so $x = 6$.",
  },
  {
    id: "lin-2",
    statement:
      "Ann is twice as old as Ben. In $6$ years, the sum of their ages will be $42$. How old is Ann now?",
    answerType: "integer",
    answer: 20,
    difficulty: 4,
    estMinutes: 3,
    topicId: "linear-equations",
    subtopic: "Age word problems",
    source: "AMC 8 style",
    tags: ["word-problems", "modeling"],
    hints: [
      "Name Ben's age $b$; then Ann's age is $2b$.",
      "In 6 years each is 6 years older: $(2b+6) + (b+6) = 42$.",
      "Solve $3b + 12 = 42$.",
    ],
    solution:
      "Let Ben be $b$, Ann $2b$. Then $(2b+6)+(b+6) = 42$ gives $3b = 30$, $b = 10$, so Ann is $20$.",
    commonMistakes: ["Adding 6 years to only one person.", "Reporting Ben's age instead of Ann's."],
  },
  {
    id: "lin-3",
    statement:
      "Pipe A fills a tank in $6$ hours; pipe B fills it in $3$ hours. Working together, how many hours do they take?",
    answerType: "mcq",
    choices: ["$1.5$", "$2$", "$2.5$", "$3$", "$4.5$"],
    answer: 1,
    difficulty: 5,
    estMinutes: 3,
    topicId: "linear-equations",
    subtopic: "Work rates",
    source: "AMC 10 style",
    tags: ["rates", "work"],
    hints: [
      "Think in tanks per hour, not hours per tank.",
      "A fills $\\tfrac{1}{6}$ per hour; B fills $\\tfrac{1}{3}$ per hour.",
      "Combined rate $\\tfrac{1}{6}+\\tfrac{1}{3} = \\tfrac{1}{2}$ tank per hour.",
    ],
    solution:
      "Rates add: $\\tfrac16 + \\tfrac13 = \\tfrac12$ tank/hour, so the tank takes $2$ hours.",
    commonMistakes: ["Averaging the times ($4.5$) — times don't add, rates do."],
  },
  {
    id: "ineq-1",
    statement:
      "How many integers $n$ satisfy $3n - 5 < 16 < 5n - 4$?",
    answerType: "integer",
    answer: 2,
    difficulty: 4,
    estMinutes: 3,
    topicId: "inequalities-basic",
    subtopic: "Compound inequalities",
    source: "AMC 10 style",
    tags: ["inequalities", "integer-solutions"],
    hints: [
      "Split into two separate inequalities.",
      "From $3n - 5 < 16$: $n < 7$. Now the other side.",
      "From $16 < 5n - 4$: $n > 4$.",
    ],
    solution:
      "$3n-5 < 16 \\Rightarrow n < 7$ and $16 < 5n - 4 \\Rightarrow n > 4$. Integers strictly between: $n = 5, 6$ — two of them.",
    commonMistakes: ["Including the endpoints — both inequalities are strict."],
  },
  {
    id: "coord-1",
    statement: "What is the distance between $(1, 2)$ and $(7, 10)$?",
    answerType: "integer",
    answer: 10,
    difficulty: 3,
    estMinutes: 2,
    topicId: "coordinate-plane",
    subtopic: "Distance formula",
    source: "AMC 8 style",
    tags: ["distance", "pythagorean"],
    hints: [
      "Draw the right triangle with legs parallel to the axes.",
      "The legs have lengths $6$ and $8$.",
      "Recognize the $6$–$8$–$10$ triple.",
    ],
    solution:
      "$\\sqrt{(7-1)^2 + (10-2)^2} = \\sqrt{36+64} = \\sqrt{100} = 10$ — a scaled $3$–$4$–$5$ triangle.",
  },
  {
    id: "coord-2",
    statement:
      "A line passes through $(2, 3)$ and $(6, 11)$. If its equation is $y = mx + b$, what is $m + b$?",
    answerType: "integer",
    answer: 1,
    difficulty: 4,
    estMinutes: 3,
    topicId: "coordinate-plane",
    subtopic: "Slope-intercept form",
    source: "AMC 10 style",
    tags: ["lines", "slope"],
    hints: [
      "Slope first: rise over run between the two points.",
      "$m = \\tfrac{11-3}{6-2} = 2$. Now find $b$.",
      "Substitute $(2,3)$: $3 = 2 \\cdot 2 + b$.",
    ],
    solution:
      "$m = \\tfrac{8}{4} = 2$; then $3 = 4 + b$ gives $b = -1$, so $m + b = 1$.",
  },
  {
    id: "expr-1",
    statement: "If $x + \\tfrac{1}{x} = 5$, what is $x^2 + \\tfrac{1}{x^2}$?",
    answerType: "integer",
    answer: 23,
    difficulty: 4,
    estMinutes: 3,
    topicId: "expressions",
    subtopic: "Symmetric manipulation",
    source: "AMC 10 style",
    tags: ["identities", "symmetric"],
    hints: [
      "Don't solve for $x$ — square the given equation.",
      "$(x + \\tfrac1x)^2 = x^2 + 2 + \\tfrac{1}{x^2}$.",
      "So $x^2 + \\tfrac1{x^2} = 25 - 2$.",
    ],
    solution:
      "Squaring: $x^2 + 2 + \\tfrac1{x^2} = 25$, so $x^2 + \\tfrac1{x^2} = 23$. The cross term is the whole trick.",
    commonMistakes: ["Trying to find $x$ itself — it's irrational and unnecessary."],
    related: ["quad-2", "sys-2"],
  },
];
