import type { Problem } from "@/lib/types";

export const NUMBER_THEORY_PROBLEMS: Problem[] = [
  {
    id: "div-1",
    statement: "How many positive divisors does $36$ have?",
    answerType: "integer",
    answer: 9,
    difficulty: 3,
    estMinutes: 2,
    topicId: "divisibility",
    subtopic: "Divisor counting",
    source: "AMC 8 style",
    tags: ["divisors", "factorization"],
    hints: [
      "Factor into primes first.",
      "$36 = 2^2 \\cdot 3^2$.",
      "Each divisor picks an exponent for each prime: $(2+1)(2+1)$.",
    ],
    solution:
      "$36 = 2^2 3^2$, so the divisor count is $(2+1)(2+1) = 9$.",
  },
  {
    id: "div-2",
    statement: "What is $\\gcd(84, 126)$?",
    answerType: "integer",
    answer: 42,
    difficulty: 4,
    estMinutes: 2,
    topicId: "divisibility",
    subtopic: "GCD",
    source: "AMC 8 style",
    tags: ["gcd", "euclidean"],
    hints: [
      "Factor both, or run the Euclidean algorithm.",
      "$84 = 2^2 \\cdot 3 \\cdot 7$, $126 = 2 \\cdot 3^2 \\cdot 7$.",
      "Take the minimum exponent of each prime.",
    ],
    solution:
      "$\\gcd = 2^1 \\cdot 3^1 \\cdot 7^1 = 42$. (Euclid: $\\gcd(84,126) = \\gcd(84,42) = 42$.)",
  },
  {
    id: "div-3",
    statement: "What is the smallest positive integer with exactly $6$ divisors?",
    answerType: "integer",
    answer: 12,
    difficulty: 5,
    estMinutes: 3,
    topicId: "divisibility",
    subtopic: "Divisor counting, reversed",
    source: "AMC 10 style",
    tags: ["divisors", "optimization"],
    hints: [
      "Which exponent patterns give 6 divisors?",
      "$6 = 6$ or $6 = 2 \\cdot 3$: shapes $p^5$ or $p^2 q$.",
      "Minimize each shape with the smallest primes.",
    ],
    solution:
      "Divisor count $6$ forces shape $p^5$ (smallest: $32$) or $p^2 q$ (smallest: $2^2 \\cdot 3 = 12$). Answer: $12$.",
  },
  {
    id: "div-4",
    statement:
      "Two positive integers have $\\gcd = 6$ and $\\text{lcm} = 180$. If one of them is $36$, what is the other?",
    answerType: "integer",
    answer: 30,
    difficulty: 6,
    estMinutes: 3,
    topicId: "divisibility",
    subtopic: "gcd·lcm identity",
    source: "AMC 10 style",
    tags: ["gcd", "lcm"],
    hints: [
      "There's an identity connecting gcd, lcm, and the product.",
      "$\\gcd(a,b) \\cdot \\text{lcm}(a,b) = ab$.",
      "$6 \\cdot 180 = 36 \\cdot b$.",
    ],
    solution:
      "$ab = \\gcd \\cdot \\text{lcm} = 1080$, so $b = 1080/36 = 30$. Check: $\\gcd(36,30) = 6$, $\\text{lcm} = 180$. ✓",
  },
  {
    id: "div-5",
    statement: "In how many zeros does $25!$ end?",
    answerType: "integer",
    answer: 6,
    difficulty: 6,
    estMinutes: 3,
    topicId: "divisibility",
    subtopic: "Legendre's formula",
    source: "AMC 10 style",
    tags: ["factorials", "trailing-zeros"],
    hints: [
      "Trailing zeros come from factors of $10 = 2 \\cdot 5$.",
      "Fives are scarcer than twos — count factors of 5 in $25!$.",
      "$\\lfloor 25/5 \\rfloor + \\lfloor 25/25 \\rfloor$.",
    ],
    solution:
      "Count of $5$s: $\\lfloor 25/5\\rfloor + \\lfloor 25/25\\rfloor = 5 + 1 = 6$ (note $25$ contributes two). Six trailing zeros.",
    commonMistakes: ["Counting multiples of 5 as one factor each — 25 carries two."],
  },
  {
    id: "prime-1",
    statement:
      "For how many primes $p$ are $p$, $p+2$, and $p+4$ all prime?",
    answerType: "integer",
    answer: 1,
    difficulty: 5,
    estMinutes: 3,
    topicId: "divisibility",
    subtopic: "Prime patterns",
    source: "AMC 10 style",
    tags: ["primes", "modular-argument"],
    hints: [
      "Try small cases, then look for an obstruction.",
      "Consider $p, p+2, p+4$ modulo $3$.",
      "One of any three numbers spaced by 2 is divisible by 3.",
    ],
    solution:
      "Mod $3$, the numbers $p, p+2, p+4$ hit all three residues, so one is divisible by $3$. That one must be $3$ itself, forcing $p = 3$: indeed $3, 5, 7$ works — and it's the only case. Answer: $1$ prime.",
  },
  {
    id: "mod-1",
    statement: "What is the remainder when $2^{10}$ is divided by $7$?",
    answerType: "integer",
    answer: 2,
    difficulty: 4,
    estMinutes: 2,
    topicId: "modular",
    subtopic: "Power cycles",
    source: "AMC 8 style",
    tags: ["remainders", "cycles"],
    hints: [
      "Find the cycle of powers of 2 mod 7.",
      "$2^1, 2^2, 2^3 \\equiv 2, 4, 1 \\pmod 7$ — period 3.",
      "$10 = 3 \\cdot 3 + 1$.",
    ],
    solution:
      "$2^3 \\equiv 1 \\pmod 7$, so $2^{10} = (2^3)^3 \\cdot 2 \\equiv 2 \\pmod 7$.",
  },
  {
    id: "mod-2",
    statement: "What is the units digit of $7^{2026}$?",
    answerType: "integer",
    answer: 9,
    difficulty: 5,
    estMinutes: 3,
    topicId: "modular",
    subtopic: "Units digit cycles",
    source: "AMC 8 style",
    tags: ["units-digit", "cycles"],
    hints: [
      "Units digits of powers repeat in a short cycle.",
      "$7^1, 7^2, 7^3, 7^4$ end in $7, 9, 3, 1$ — period 4.",
      "Find $2026 \\bmod 4$.",
    ],
    solution:
      "The cycle is $7,9,3,1$ with period $4$; $2026 \\equiv 2 \\pmod 4$, so the units digit matches $7^2$: it is $9$.",
  },
  {
    id: "mod-3",
    statement: "What is the remainder when $3^{100}$ is divided by $8$?",
    answerType: "integer",
    answer: 1,
    difficulty: 5,
    estMinutes: 2,
    topicId: "modular",
    subtopic: "Power cycles",
    source: "AMC 10 style",
    tags: ["remainders", "cycles"],
    hints: [
      "Compute the first couple of powers mod 8.",
      "$3^2 = 9 \\equiv 1 \\pmod 8$.",
      "$3^{100} = (3^2)^{50}$.",
    ],
    solution:
      "$3^2 \\equiv 1 \\pmod 8$, so $3^{100} = (3^2)^{50} \\equiv 1 \\pmod 8$.",
  },
  {
    id: "mod-4",
    statement:
      "What is the smallest positive integer $x$ with $x \\equiv 2 \\pmod 5$ and $x \\equiv 3 \\pmod 7$?",
    answerType: "integer",
    answer: 17,
    difficulty: 6,
    estMinutes: 4,
    topicId: "modular",
    subtopic: "Simultaneous congruences",
    source: "AMC 10 style",
    tags: ["crt", "congruences"],
    hints: [
      "List numbers that are $2$ mod $5$ and test mod 7.",
      "$2, 7, 12, 17, 22, \\ldots$",
      "$17 = 2 \\cdot 7 + 3$.",
    ],
    solution:
      "Scanning $x \\equiv 2 \\pmod 5$: $2, 7, 12, 17$ — and $17 \\equiv 3 \\pmod 7$. ✓ (CRT guarantees a unique answer mod $35$.)",
    related: ["tot-2"],
  },
  {
    id: "mod-5",
    statement:
      "What is the units digit of $1! + 2! + 3! + \\cdots + 100!$?",
    answerType: "integer",
    answer: 3,
    difficulty: 6,
    estMinutes: 3,
    topicId: "modular",
    subtopic: "Factorials mod 10",
    source: "AMC 10 style",
    tags: ["factorials", "units-digit"],
    hints: [
      "What is the units digit of $5!$, $6!$, and beyond?",
      "From $5!$ on, every factorial ends in $0$.",
      "Only $1! + 2! + 3! + 4!$ matters.",
    ],
    solution:
      "$n!$ ends in $0$ for $n \\ge 5$, so the units digit is that of $1+2+6+24 = 33$: it is $3$.",
  },
  {
    id: "dio-1",
    statement:
      "How many ordered pairs of positive integers $(x, y)$ satisfy $xy + 3x + 2y = 30$?",
    answerType: "integer",
    answer: 4,
    difficulty: 6,
    estMinutes: 5,
    topicId: "diophantine",
    subtopic: "Simon's Favorite Factoring Trick",
    source: "AIME style",
    tags: ["sfft", "factoring"],
    hints: [
      "Add a constant to make the left side factor.",
      "$xy + 3x + 2y + 6 = (x+2)(y+3)$.",
      "So $(x+2)(y+3) = 36$ with $x+2 \\ge 3$, $y+3 \\ge 4$.",
    ],
    solution:
      "Adding $6$: $(x+2)(y+3) = 36$. Factor pairs with $x+2 \\ge 3$ and $y+3 \\ge 4$: $(3,12), (4,9), (6,6), (9,4)$ — giving $(x,y) = (1,9), (2,6), (4,3), (7,1)$. Four pairs.",
    commonMistakes: ["Missing the constraint that $x, y$ must be positive, which kills $(12,3)$."],
  },
  {
    id: "dio-2",
    statement:
      "How many ordered pairs of positive integers $(x, y)$ satisfy $3x + 5y = 47$?",
    answerType: "integer",
    answer: 3,
    difficulty: 6,
    estMinutes: 4,
    topicId: "diophantine",
    subtopic: "Linear Diophantine",
    source: "AMC 10 style",
    tags: ["linear-diophantine", "modular"],
    hints: [
      "Reduce mod 3 to constrain $y$.",
      "$47 \\equiv 2$, $5y \\equiv 2y \\pmod 3$, so $y \\equiv 1 \\pmod 3$.",
      "Check $y = 1, 4, 7$ against $5y < 47$.",
    ],
    solution:
      "Mod $3$: $2y \\equiv 2$, so $y \\equiv 1 \\pmod 3$: $y \\in \\{1, 4, 7\\}$ (since $5y < 47$), giving $x = 14, 9, 4$. Three pairs.",
  },
  {
    id: "dio-3",
    statement:
      "How many ordered pairs of positive integers $(x, y)$ satisfy $x^2 - y^2 = 45$?",
    answerType: "integer",
    answer: 3,
    difficulty: 7,
    estMinutes: 5,
    topicId: "diophantine",
    subtopic: "Difference of squares",
    source: "AIME style",
    tags: ["factoring", "parity"],
    hints: [
      "Factor the left side.",
      "$(x-y)(x+y) = 45$ — and both factors have the same parity.",
      "$45$ is odd, so both factors are odd: pair up odd divisors with $x - y < x + y$.",
    ],
    solution:
      "$(x-y)(x+y) = 45$ with both factors odd and $x-y < x+y$: $(1,45), (3,15), (5,9)$ give $(x,y) = (23,22), (9,6), (7,2)$. Three pairs.",
  },
  {
    id: "tot-1",
    statement: "What is $\\varphi(100)$, the number of integers in $[1,100]$ coprime to $100$?",
    answerType: "integer",
    answer: 40,
    difficulty: 7,
    estMinutes: 3,
    topicId: "totient-crt",
    subtopic: "Euler's totient",
    source: "AMC 12 style",
    tags: ["totient"],
    hints: [
      "Use the product formula over prime factors.",
      "$100 = 2^2 \\cdot 5^2$.",
      "$\\varphi(100) = 100 \\left(1 - \\tfrac12\\right)\\left(1 - \\tfrac15\\right)$.",
    ],
    solution:
      "$\\varphi(100) = 100 \\cdot \\tfrac12 \\cdot \\tfrac45 = 40$.",
  },
  {
    id: "tot-2",
    statement: "What are the last two digits of $7^{222}$?",
    answerType: "integer",
    answer: 49,
    difficulty: 8,
    estMinutes: 5,
    topicId: "totient-crt",
    subtopic: "Order-finding",
    source: "AIME style",
    tags: ["totient", "cycles", "mod-100"],
    hints: [
      "You need $7^{222} \\bmod 100$. Find the cycle length of powers of 7.",
      "$7^2 = 49$, $7^3 = 343 \\equiv 43$, $7^4 \\equiv 43 \\cdot 7 = 301 \\equiv 1 \\pmod{100}$.",
      "The order is $4$; reduce $222$ mod $4$.",
    ],
    solution:
      "$7^4 \\equiv 1 \\pmod{100}$, and $222 \\equiv 2 \\pmod 4$, so $7^{222} \\equiv 7^2 = 49$. Last two digits: $49$.",
    altSolutions: ["Euler gives $7^{40} \\equiv 1$; the actual order $4$ divides $40$ and shortens the work."],
    related: ["mod-2"],
  },
];
