// Only independently reviewed lessons belong here.
export const PUBLISHED_LESSONS = new Set([
  "course:amc-8:permutations-definition",
  "course:amc-8:factorials",
  "course:amc-8:permutations-fundamentals",
  "course:amc-8:digit-permutations",
  "course:amc-8:circular-arrangements",
  "course:amc-8:combinations-fundamentals",
  "course:amc-8:binomial-identity",
  "course:amc-8:tricky-combinations",
  "course:amc-8:word-rearrangements-fundamentals",
  "course:amc-8:word-rearrangements-with-constraints",
  "course:amc-8:probability-fundamentals",
  "course:amc-8:distinguishability",
  "course:amc-8:casework-in-probability",
  "course:amc-8:independent-events-probability",
  "course:amc-8:dependent-events-probability",
  "course:amc-8:dependent-or-independent",
  "course:amc-10-12:bounds-and-extrema",
  "course:amc-10-12:congruences-cycles-and-remainders",
  "course:amc-10-12:domains-composition-inverses-and-graphs",
  "course:amc-10-12:factor-expressions-and-simplify-radicals",
  "course:amc-10-12:integer-equations-and-place-value",
  "course:amc-10-12:polynomial-roots-and-symmetric-relationships",
  "course:amc-10-12:prime-powers-and-divisor-structure",
  "course:amc-10-12:quadratics-discriminants-and-intersections",
  "course:amc-10-12:systems-and-equation-restrictions",
]);
